# Generated by scripts/update-formula.sh - do not edit by hand.
class Shist < Formula
  desc "Sean's History Tool (a shell history tool)"
  homepage "https://github.com/seanmizen/shist"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/seanmizen/shist/releases/download/v1.0.1/shist_1.0.1_darwin_arm64.tar.gz"
      sha256 "80401bdc1ddb6bbd32b71ecf353fbee7342905fe36ad291d0cfdbafd839eced0"
    end
    on_intel do
      url "https://github.com/seanmizen/shist/releases/download/v1.0.1/shist_1.0.1_darwin_amd64.tar.gz"
      sha256 "071aca4ee7583d08ff344d1590e19b083b724166649d435fe0b5b1f735859f58"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/seanmizen/shist/releases/download/v1.0.1/shist_1.0.1_linux_arm64.tar.gz"
      sha256 "6967741ce07ac5eef17d11ccd720f07f1dd08f46220b258dac88059503bee72b"
    end
    on_intel do
      url "https://github.com/seanmizen/shist/releases/download/v1.0.1/shist_1.0.1_linux_amd64.tar.gz"
      sha256 "4b5b51b23d9d0cec682b84f60a995e51342ae08f99174f8f18c768251759f1e7"
    end
  end

  def install
    bin.install "shist"
  end

  test do
    assert_match "shist #{version}", shell_output("#{bin}/shist -v")
  end
end
