# Generated by scripts/update-formula.sh - do not edit by hand.
class Shist < Formula
  desc "Sean's History Tool (a shell history tool)"
  homepage "https://github.com/seanmizen/shist"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/seanmizen/shist/releases/download/v1.1.0/shist_1.1.0_darwin_arm64.tar.gz"
      sha256 "2dbdb426d8d858c453343bb84d175a839df3ac5671b66afc39c1691e4559b50a"
    end
    on_intel do
      url "https://github.com/seanmizen/shist/releases/download/v1.1.0/shist_1.1.0_darwin_amd64.tar.gz"
      sha256 "d5fa1f24f4fcfdd704c02bb1d0cc1e2e3500eea1a1a6e8bd56da612d6e8e1df6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/seanmizen/shist/releases/download/v1.1.0/shist_1.1.0_linux_arm64.tar.gz"
      sha256 "ae621841d36b99548e1f7b81917c2b718ce2e0438103095893a1520db32f4150"
    end
    on_intel do
      url "https://github.com/seanmizen/shist/releases/download/v1.1.0/shist_1.1.0_linux_amd64.tar.gz"
      sha256 "abf72b01e2d089888898f85124c69334c79a728788a51489bc83a0ff3b444011"
    end
  end

  def install
    bin.install "shist"
  end

  test do
    assert_match "shist #{version}", shell_output("#{bin}/shist -v")
  end
end
