#!/usr/bin/env bash
# Regenerate Formula/shist.rb from a published shist release.
# Usage: scripts/update-formula.sh [tag]   (default: latest release)
set -euo pipefail

REPO="seanmizen/shist"
TAG="${1:-}"
[ -n "$TAG" ] || TAG="$(gh release view -R "$REPO" --json tagName --jq .tagName)"
VER="${TAG#v}"

SUMS="$(gh release download "$TAG" -R "$REPO" -p checksums.txt -O -)"

sum() { # sum <os>_<arch> <ext>
  awk -v f="shist_${VER}_$1.$2" '$2 == f { print $1 }' <<<"$SUMS"
}
url() { echo "https://github.com/$REPO/releases/download/$TAG/shist_${VER}_$1.$2"; }

for t in darwin_arm64 darwin_amd64 linux_arm64 linux_amd64; do
  [ -n "$(sum "$t" tar.gz)" ] || { echo "missing checksum for $t in $TAG" >&2; exit 1; }
done

cat > Formula/shist.rb <<RB
# Generated by scripts/update-formula.sh - do not edit by hand.
class Shist < Formula
  desc "Sean's History Tool (a shell history tool)"
  homepage "https://github.com/$REPO"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url darwin_arm64 tar.gz)"
      sha256 "$(sum darwin_arm64 tar.gz)"
    end
    on_intel do
      url "$(url darwin_amd64 tar.gz)"
      sha256 "$(sum darwin_amd64 tar.gz)"
    end
  end

  on_linux do
    on_arm do
      url "$(url linux_arm64 tar.gz)"
      sha256 "$(sum linux_arm64 tar.gz)"
    end
    on_intel do
      url "$(url linux_amd64 tar.gz)"
      sha256 "$(sum linux_amd64 tar.gz)"
    end
  end

  def install
    bin.install "shist"
  end

  test do
    assert_match "shist #{version}", shell_output("#{bin}/shist -v")
  end
end
RB

echo "wrote Formula/shist.rb for $TAG"
